T=read.csv(file.choose())
ss=ts(T)
ss
plot(ss, main="nombre",ylab="days",col="blue")
plot(ss, main="nombre",ylab="period",col="blue")
library('tseries')
library('ggplot2')
library('forecast')
Acf(ss, main='')
Pacf(ss,main='')
auto.arima(ss)
forecast(auto.arima(ss))
plot(forecast(auto.arima(ss)))
library('moments')
library('nortest')
jarque.bera.test(ss)
ad.test(ss)
lillie.test(ss)
pearson.test(ss)
sf.test(ss)
shapiro.test(ss)
qqnorm(ss)
qqline(ss)
hist(ss)
